server:
  port: 8761
spring:
  profiles: peer1
  application:
    name: simple-eureka
eureka:
  instance:
    ip-address: 192.168.1.7
    prefer-ip-address: true
  server:
    enableSelfPreservation: false #关闭自我保护，默认60秒后剔除失效服务
#    evictionIntervalTimerInMs: 4000 默认60s
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    service-url:
      defaultZone: http://eureka:eureka@192.168.1.21:8761/eureka/
          
security: #开启认证
  basic:
    enabled: true
  user:
    name: eureka
    password: eureka